### ISSUE TITLE
add missing key type added in psono server 2.4

### ISSUE THREAD

**Issue by JanKraljic** [meldron/psonoci#6]
psonoci is missing the types SSH private key and SSH public key that was added in psono 2.4

i don't know internal structure but i assume there is missing secret-value-type: 
* ssh_key_private
* ssh_key_public

I think _bookmark_ is not in psonoci too, but I would not recommend to put Credit cart to psonoci

### From release notes

- Feature: Added SSH key entry type
- Feature: Added credit card type

**Comment by meldron** [comment]
[v0.4.0](https://github.com/meldron/psonoci/releases/tag/v0.4.0) introduces SSH key, credit card and TOTP secret types.
